import requests
import json

uri = "https://voyfinance.instance.kyc-chain.com/integrations/v3/scope/voyfinance/data-checks/entity?countryCodes=GB&countryCodes=US&name=Cargill%20Incorporated"
# uri = "https://voyfinance.instance.kyc-chain.com/integrations/v3/scope/voyfinance/wallet-screening/"
# uri = "https://voyfinance.instance.kyc-chain.com/integrations/v3/scope/voyfinance/risk-scoring/scorecard/"
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OTg0ODFjOGM2MjEzODFjNTBjYzY1MCIsInJvbGVzIjpbeyJfaWQiOiI2NTJlMzhkMGNmNzk2NjZkNGQ5MjI5MTQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsIl9fdiI6MCwiY3JlYXRlZEF0IjoiMjAyMy0xMC0xN1QwNzozMzozNi42MzRaIiwiaW50ZXJuYWwiOmZhbHNlLCJsb2NrZWQiOnRydWUsInBlcm1pc3Npb25zIjpbInZpZXdfZGFzaGJvYXJkIiwidmlld19jb3Jwb3JhdGUiLCJpbnZpdGVfY29ycG9yYXRlIiwiYXNzaWduX2NvcnBvcmF0ZSIsInZpZXdfdW5hc3NpZ25lZF9jb3Jwb3JhdGUiLCJ2aWV3X2Fzc2lnbmVkX290aGVyc19jb3Jwb3JhdGUiLCJ2aWV3X2luZGl2aWR1YWwiLCJpbnZpdGVfaW5kaXZpZHVhbCIsImFzc2lnbl9pbmRpdmlkdWFsIiwidmlld191bmFzc2lnbmVkX2luZGl2aWR1YWwiLCJ2aWV3X2Fzc2lnbmVkX290aGVyc19pbmRpdmlkdWFsIiwicmVxdWVzdF9hZGRpdGlvbmFsX3JlcXVpcmVtZW50cyIsImludmFsaWRhdGVfcmVxdWlyZW1lbnRzIiwiZWRpdF9yaXNrX3Njb3JlcyIsInVzZV9tYW5hZ2VyX2ZpbGwiLCJtYWtlX2FwcHJvdmFsX2RlY2lzaW9ucyIsInN1Ym1pdF9kYXRhIiwic2VuZF9tZXNzYWdlcyIsImNvbmZpcm1fZXh0ZXJuYWxfaGl0cyIsInVzZV93YWxsZXRfc2NyZWVuaW5nIiwiYWRkX25vdGVzIiwidmlld19hcHBsaWNhbnRfZmlsZXMiLCJkb3dubG9hZF9hcHBsaWNhbnRfZmlsZXMiLCJ2aWV3X2t5Y190ZW1wbGF0ZXMiLCJjcmVhdGVfa3ljX3RlbXBsYXRlIiwiZGVsZXRlX2t5Y190ZW1wbGF0ZSIsImVkaXRfa3ljX3RlbXBsYXRlIiwidmlld19kb2NfdGVtcGxhdGVzIiwiY3JlYXRlX2RvY190ZW1wbGF0ZSIsImRlbGV0ZV9kb2NfdGVtcGxhdGUiLCJlZGl0X2RvY190ZW1wbGF0ZSIsInZpZXdfZXhwb3J0Iiwidmlld19zZWFyY2hfZGF0YWJhc2VzIiwidmlld19hcHBsaWNhbnRfbWFuYWdlbWVudCIsInZpZXdfcmlza19zY29yZV9jYXJkcyIsInZpZXdfcmVtaW5kZXJzX3NldHRpbmdzIiwidmlld19ub3RlX3RlbXBsYXRlc19zZXR0aW5ncyIsInZpZXdfbWVzc2FnZXNfc2V0dGluZ3MiLCJ2aWV3X2VtYWlsX21hbmFnZW1lbnQiLCJ2aWV3X2FwaWtleXMiLCJ2aWV3X2JpbGxpbmdfaW5mbyIsImVkaXRfYmFzaWNfc2NvcGUiLCJlZGl0X3Njb3BlX2xvZ28iLCJ2aWV3X2Zsb3dfc2V0dGluZ3MiLCJjcmVhdGVfY2hpbGRfc2NvcGUiLCJhc3NpZ25fbWFuYWdlcl90b19jaGlsZF9zY29wZSIsImFkZF9tZW1iZXJfYXBwbGljYXRpb24iLCJlZGl0X21lbWJlcl9hcHBsaWNhdGlvbiIsImRlbGV0ZV9tZW1iZXJfYXBwbGljYXRpb24iLCJvcmRlcl9kb2N1bWVudHMiLCJ2aWV3X21hbmFnZXJfcGVybWlzc2lvbnMiXSwic2NvcGUiOiI2MDhhN2VkNGRiODVlZTg2YzQ3YjRhZGQiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTI4VDAzOjQxOjUwLjc0NFoifV0sInNjb3BlcyI6WyI2MDhhN2VkNGRiODVlZTg2YzQ3YjRhZGQiXSwia2V5SWQiOiI2NTk4NDkwNDhjNjIxMzgxYzUwY2M4YzAiLCJpYXQiOjE3MDQ0Nzg5ODAsImV4cCI6MTczNjAxNDk4MCwiYXVkIjoiYXBpa2V5IiwiaXNzIjoia3ljYy1lbnZveV82MDhhN2VkNGRiODVlZTg2YzQ3YjRhZGQiLCJzdWIiOiI2NTk4NDgxYzhjNjIxMzgxYzUwY2M2NTAifQ.0dJvOFSnWd3FjlF1-lJyZFQF6KItIqjisYt7imRZyXE"

# HTTP header fields to set
headers = {
    "apiKey": token,
    "accept": "application/json",
}
# make request
r = requests.get(uri, headers=headers, verify=False)

# print the result
# print(r.keys())
# for key in r.text:
#     print(key)

res = r.json()
# res = res["complyAdvantageEntities"]

print(json.dumps(res, indent=4, sort_keys=True))
# print(res.keys())


file1 = open("data_checks.txt", "w")
file1.writelines(str(res))
file1.close()
